// var ontology = [['Other', 0, '#888888', 'Other'],
//     ['Activity', 1, '#F08080', 'Activity'],
//
//     ['Agent', 1, '#2E7866', 'Agent'],
//     ['FictionalCharacter', 2, '#20B2AA', 'Agent.<br/>FictionalCharacter'],
//     ['Organisation', 2, '#63B931', 'Agent.<br/>Organisation'],
//     ['Broadcaster', 3, '#71BF43', 'Agent.<br/>Organisation.<br/>Broadcaster'],
//     ['Company', 3, '#7FC556', 'Agent.<br/>Organisation.<br/>Company'],
//     ['EducationalInstitution', 3, '#8DCC69', 'Agent.<br/>Organisation.<br/>EducationalInstitution'],
//     ['MilitaryUnit', 3, '#9BD27B', 'Agent.<br/>Organisation.<br/>MilitaryUnit'],
//     ['PoliticalParty', 3, '#A9D88E', 'Agent.<br/>Organisation.<br/>PoliticalParty'],
//     ['SportsLeague', 3, '#B8DFA1', 'Agent.<br/>Organisation.<br/>SportsLeague'],
//     ['SportsTeam', 3, '#C6E5B4', 'Agent.<br/>Organisation.<br/>SportsTeam'],
//     ['Person', 2, '#ff7473', 'Agent.<br/>Person'],
//     ['Architect', 3, '#FF807F', 'Agent.<br/>Person.<br/>Architect'],
//     ['Artist', 3, '#FF8D8C', 'Agent.<br/>Person.<br/>Artist'],
//     ['Astronaut', 3, '#FF9999', 'Agent.<br/>Person.<br/>Astronaut'],
//     ['Athlete', 3, '#FFA6A5', 'Agent.<br/>Person.<br/>Athlete'],
//     ['MilitaryPerson', 3, '#FFB3B2', 'Agent.<br/>Person.<br/>MilitaryPerson'],
//     ['Scientist', 3, '#FFBFBF', 'Agent.<br/>Person.<br/>Scientist'],
//
//     ['AnatomicalStructure', 1, '#4B0370', 'AnatomicalStructure'],
//     ['Artery', 2, '#5B197D', 'AnatomicalStructure.<br/>Artery'],
//     ['Embryology', 2, '#6B308A', 'AnatomicalStructure.<br/>Embryology'],
//     ['Lymph', 2, '#7C4797', 'AnatomicalStructure.<br/>Lymph'],
//     ['Nerve', 2, '#8C5EA4', 'AnatomicalStructure.<br/>Nerve'],
//     ['Vein', 2, '#9C75B1', 'AnatomicalStructure.<br/>Vein'],
//
//     ['MeanOfTransportation', 1, '#D06825', 'MeanOfTransportation'],
//     ['Automobile', 2, '#D47538', 'MeanOfTransportation.<br/>Automobile'],
//     ['Rocket', 2, '#DC9160', 'MeanOfTransportation.<br/>Rocket'],
//     ['SpaceShuttle', 2, '#E5AC88', 'MeanOfTransportation.<br/>SpaceShuttle'],
//
//     ['Place', 1, '#070640', 'Place'],
//     ['ArchitecturalStructure', 2, '#0B0A6B', 'Place.<br/>ArchitecturalStructure'],
//     ['Building', 3, '#0B0A6B', 'Place.ArchitecturalStructure.<br/>Building'],
//     ['PopulatedPlace', 2, '#222081', 'Place.<br/>PopulatedPlace'],
//     ['Country', 3, '#38368E', 'Place.<br/>PopulatedPlace.<br/>Country'],
//     ['Island', 3, '#4E4C9A', 'Place.<br/>PopulatedPlace.<br/>Island'],
//     ['Settlement', 3, '#6463A7', 'Place.<br/>PopulatedPlace.<br/>Settlement'],
//     ['NaturalPlace', 2, '#7A79B3', 'Place.<br/>NaturalPlace'],
//     ['BodyOfWater', 3, '#908FC0', 'Place.<br/>NaturalPlace.<br/>BodyOfWater'],
//     ['Mountain', 3, '#A6A5CC', 'Place.<br/>NaturalPlace.<br/>Mountain'],
//
//     ['Work', 1, '#45300C', 'Work'],
//     ['Film', 2, '#674812', 'Work.<br/>Film'],
//     ['MusicalWork', 2, '#896118', 'Work.<br/>MusicalWork'],
//     ['Album', 3, '#AA5555', 'Work.<br/>MusicalWork.<br/>Album'],
//     ['Musical', 3, '#8B4513', 'Work.<br/>MusicalWork.<br/>Musical'],
//     ['Single', 3, '#8B4513', 'Work.<br/>MusicalWork.<br/>Single'],
//     ['Software', 2, '#AB781E', 'Work.<br/>Software.'],
//     ['VideoGame', 3, '#D2691E', 'Work.<br/>Software.<br/>VideoGame'],
//     ['TelevisionEpisode', 2, '#C28F34', 'Work.<br/>TelevisionEpisode'],
//     ['TelevisionShow', 2, '#CEA55C', 'Work.<br/>TelevisionShow'],
//     ['WrittenWork', 2, '#DABB85', 'Work.<br/>WrittenWork'],
//
//     ['TropicalConcept', 1, '#2E768F', 'TropicalConcept'],
//     ['Genre', 2, '#3486A3', 'TropicalConcept.<br/>Genre'],
//     ['MusicGenre', 3, '#3486A3', 'TropicalConcept.<br/>Genre.<br/>MusicGenre'],
//     ['Ideology', 2, '#3B97B8', 'TropicalConcept.<br/>Ideology'],
//     ['Type', 2, '#47B8E0', 'TropicalConcept.<br/>Type'],
//     ['GovernmentType', 3, '#47B8E0', 'TropicalConcept.<br/>Type.<br/>GovernmentType'],
//
//     ['Device', 1, '#694853', 'Device'],
//     ['Instrument', 2, '#8C616E', 'Device.<br/>Instrument'],
//     ['Engine', 2, '#AF788A', 'Device.<br/>Engine'],
//     ['AutomobileEngine', 3, '#AF788A', 'Device.<br/>Engine.<br/>AutomobileEngine'],
//     ['Weapon', 2, '#C58FA0', 'Device.<br/>Weapon'],
//
//     ['Event', 1, '#F2C640', 'Event.'],
//     ['SocietalEvent', 2, '#F4D062', 'Event.<br/>SocietalEvent'],
//     ['FilmFestival', 3, '#F4D062', 'Event.SocietalEvent.<br/>FilmFestival'],
//     ['MilitaryConflict', 3, '#F4D062', 'Event.SocietalEvent.<br/>MilitaryConflict'],
//     ['SpaceMission', 3, '#F4D062', 'Event.SocietalEvent.<br/>SpaceMission'],
//
//     ['Award', 1, '#5F9EA0', 'Award'],
//     ['Colour', 1, '#4682B4', 'Colour'],
//     ['Currency', 1, '#808000', 'Currency'],
//     ['EthnicGroup', 1, '#2F4F4F', 'EthnicGroup'],
//     ['Language', 1, '#FFAA00', 'Language'],
//     ['Species', 1, '#CD5C5C', 'Species'],
//     ['PersonFunction', 1, '#8A2BE2', 'PersonFunction'],
//
//     // using info for NER->Ontology
//     // 171219 plo >> PLO
//     // ['Location', 1, '#2C2CA2', 'Location'],
//     // ['Person', 1, '#CC0000', 'Person'],
//     // ['Organisation', 1, '#4B784B', 'Organisation']
//
// ];
var ontology = [['Other', 0, '#888888', 'Other'],
        ['Activity', 1, '#F08080', 'Activity'],

        ['Agent', 1, '#0AFFA0', 'Agent'],
        ['FictionalCharacter', 2, '#20B2AA', 'Agent.<br/>FictionalCharacter'],
        ['Organisation', 2, '#228B22', 'Agent.<br/>Organisation'],
        ['Broadcaster', 3, '#228B22', 'Agent.<br/>Organisation.<br/>Broadcaster'],
        ['Company', 3, '#228B22', 'Agent.<br/>Organisation.<br/>Company'],
        ['EducationalInstitution', 3, '#228B22', 'Agent.<br/>Organisation.<br/>EducationalInstitution'],
        ['MilitaryUnit', 3, '#228B22', 'Agent.<br/>Organisation.<br/>MilitaryUnit'],
        ['PoliticalParty', 3, '#228B22', 'Agent.<br/>Organisation.<br/>PoliticalParty'],
        ['SportsLeague', 3, '#228B22', 'Agent.<br/>Organisation.<br/>SportsLeague'],
        ['SportsTeam', 3, '#228B22', 'Agent.<br/>Organisation.<br/>SportsTeam'],
        ['Person', 2, '#D92626', 'Agent.<br/>Person'],
        ['Architect', 3, '#D92626', 'Agent.<br/>Person.<br/>Architect'],
        ['Artist', 3, '#D92626', 'Agent.<br/>Person.<br/>Artist'],
        ['Astronaut', 3, '#D92626', 'Agent.<br/>Person.<br/>Astronaut'],
        ['Athlete', 3, '#D92626', 'Agent.<br/>Person.<br/>Athlete'],
        ['MilitaryPerson', 3, '#D92626', 'Agent.<br/>Person.<br/>MilitaryPerson'],
        ['Scientist', 3, '#D92626', 'Agent.<br/>Person.<br/>Scientist'],

        ['AnatomicalStructure', 1, '#4B0082', 'AnatomicalStructure'],
        ['Artery', 2, '#663399', 'AnatomicalStructure.<br/>Artery'],
        ['Embryology', 2, '#483D8B', 'AnatomicalStructure.<br/>Embryology'],
        ['Lymph', 2, '#800080', 'AnatomicalStructure.<br/>Lymph'],
        ['Nerve', 2, '#8A2BE2', 'AnatomicalStructure.<br/>Nerve'],
        ['Vein', 2, '#BA55D3', 'AnatomicalStructure.<br/>Vein'],

        ['MeanOfTransportation', 1, '#FF4500', 'MeanOfTransportation'],
        ['Automobile', 2, '#FF6347', 'MeanOfTransportation.<br/>Automobile'],
        ['Rocket', 2, '#FF7F50', 'MeanOfTransportation.<br/>Rocket'],
        ['SpaceShuttle', 2, '#FF8C00', 'MeanOfTransportation.<br/>SpaceShuttle'],

        ['Place', 1, '#1B1B72', 'Place'],
        ['ArchitecturalStructure', 2, '#0000CD', 'Place.<br/>ArchitecturalStructure'],
        ['Building', 3, '#0000CD', 'Place.ArchitecturalStructure.<br/>Building'],
        ['PopulatedPlace', 2, '#4169E1', 'Place.<br/>PopulatedPlace'],
        ['Country', 3, '#4169E1', 'Place.<br/>PopulatedPlace.<br/>Country'],
        ['Island', 3, '#4169E1', 'Place.<br/>PopulatedPlace.<br/>Island'],
        ['Settlement', 3, '#4169E1', 'Place.<br/>PopulatedPlace.<br/>Settlement'],
        ['NaturalPlace', 2, '#00BFFF', 'Place.<br/>NaturalPlace'],
        ['BodyOfWater', 3, '#00BFFF', 'Place.<br/>NaturalPlace.<br/>BodyOfWater'],
        ['Mountain', 3, '#00BFFF', 'Place.<br/>NaturalPlace.<br/>Mountain'],

        ['Work', 1, '#800000', 'Work'],
        ['Film', 2, '#A52A2A', 'Work.<br/>Film'],
        ['MusicalWork', 2, '#8B4513', 'Work.<br/>MusicalWork'],
        ['Album', 3, '#8B4513', 'Work.<br/>MusicalWork.<br/>Album'],
        ['Musical', 3, '#8B4513', 'Work.<br/>MusicalWork.<br/>Musical'],
        ['Single', 3, '#8B4513', 'Work.<br/>MusicalWork.<br/>Single'],
        ['Software', 2, '#D2691E', 'Work.<br/>Software.'],
        ['VideoGame', 3, '#D2691E', 'Work.<br/>Software.<br/>VideoGame'],
        ['TelevisionEpisode', 2, '#B8860B', 'Work.<br/>TelevisionEpisode'],
        ['TelevisionShow', 2, '#F4A460', 'Work.<br/>TelevisionShow'],
        ['WrittenWork', 2, '#DAA520', 'Work.<br/>WrittenWork'],

        ['TropicalConcept', 1, '#00FFFF', 'TropicalConcept'],
        ['Genre', 2, '#AFEEEE', 'TropicalConcept.<br/>Genre'],
        ['MusicGenre', 3, '#AFEEEE', 'TropicalConcept.<br/>Genre.<br/>MusicGenre'],
        ['Ideology', 2, '#7FFFD4', 'TropicalConcept.<br/>Ideology'],
        ['Type', 2, '#40E0D0', 'TropicalConcept.<br/>Type'],
        ['GovernmentType', 3, '#40E0D0', 'TropicalConcept.<br/>Type.<br/>GovernmentType'],

        ['Device', 1, '#C71585', 'Device'],
        ['Instrument', 2, '#DB7093', 'Device.<br/>Instrument'],
        ['Engine', 2, '#FF1493', 'Device.<br/>Engine'],
        ['AutomobileEngine', 3, '#FF1493', 'Device.<br/>Engine.<br/>AutomobileEngine'],
        ['Weapon', 2, '#FF69B4', 'Device.<br/>Weapon'],

        ['Event', 1, '#3F4B3B', 'Event.'],
        ['SocietalEvent', 2, '#44633F', 'Event.<br/>SocietalEvent'],
        ['SpaceMission', 3, '#3D3D00', 'Event.SocietalEvent.<br/>SpaceMission'],
        ['MilitaryConflict', 3, '#5A9367', 'Event.SocietalEvent.<br/>MilitaryConflict'],
        ['FilmFestival', 3, '#BfBF40', 'Event.SocietalEvent.<br/>FilmFestival'],

        ['Award', 1, '#5F9EA0', 'Award'],
        ['Colour', 1, '#4682B4', 'Colour'],
        ['Currency', 1, '#808000', 'Currency'],
        ['EthnicGroup', 1, '#2F4F4F', 'EthnicGroup'],
        ['Language', 1, '#FFAA00', 'Language'],
        ['Species', 1, '#CD5C5C', 'Species'],
        ['PersonFunction', 1, '#8A2BE2', 'PersonFunction'],

        // using info for NER->Ontology
        // 171219 plo >> PLO
        ['Location', 1, '#2C2CA2', 'Location'],
        ['Person', 1, '#CC0000', 'Person'],
        ['Organisation', 1, '#4B784B', 'Organisation']

    ];